apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  sensitive.data: U2VjcmV0IFN0dWZmIQo= # Secret Stuff!
  passwords.txt: U2VjcmV0IFN0dWZmIGluIGEgZmlsZSEK # Secret Stuff in a file!